title: Education Ellie
description: Software Educacional
author: Education Ellie
logo: /EducationEllie/static/img/logo.png
github: https://github.com/pedroluzio/EducationEllie
about: Software Educativo
disqus_shortname: aboutashu
#google_analytics: UA-72862926-1
urls:
    - text: Início
      url: /
      icon: fa-home
      layout: post
    - text: Sobre
      url: /about/
      icon: fa-comments
    - text: Jogos
      url: /projects/
      icon: fa-desktop
    - text: Contribuir
      url: /contribuir/
      icon: fa-code
    - text: Github
      url: https://github.com/pedroluzio/EducationEllie
      icon: fa-github
    - text: Contacto
      url: /contact/
      icon: fa-envelope
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://aboutashu.com/hcz-jekyll-blog"
baseurl: "/EducationEllie"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
